author:
  - name: Caio Aloísio Andrade Silva
    affiliation: Universidade Federal de Sergipe
  - name: Gabriel Santos de Souza
    affiliation: Universidade Federal de Sergipe
    orcid: 0009-0005-5652-617X
  - name: Lucca Pedreira Dultra
    affiliation: Universidade Federal de Sergipe
  - name: Renato Vasconcelos Campos Filho
    affiliation: Universidade Federal de Sergipe
  - name: Tarcísio Almeida Mascarenhas
    affiliation: Universidade Federal de Sergipe

bibliography: references.bib

csl: associacao-brasileira-de-normas-tecnicas.csl

editor: visual

execute:
  freeze: auto

manuscript:
  article: index.qmd

project:
  type: manuscript

format:
  html: default
  pdf:
    linkcolor: blue
    lof: true
    lot: true
    toc: true
  docx: default

lang: pt

jupyter: python3

# Coloca todas as entradas na referência independente de se foram citadas ou
# não.
nocite: |
  @*
